name: Build project

on:
  push:
    branches: [ test, master, demo ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16.x]
    env:
      working-directory: front-end

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing dependencies
      run: npm install
      working-directory: ${{env.working-directory}}

    - name: Running tests
      run: npm test
      working-directory: ${{env.working-directory}}

    - name: Building project
      run: npm run build-on:${GITHUB_REF##*/}
      working-directory: ${{env.working-directory}}

    - name: Archive build as artifact
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: ${{env.working-directory}}/build

  deploy_test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/test'
    steps:        
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_TEST_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
          AWS_REGION: ${{ secrets.AWS_REGION_TEST }}
          SOURCE_DIR: "build"