name: Deploy to test

on:
  push:
    branches: [ test, master, demo ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing dependencies
      run: npm install

    - name: Running tests
      run: npm test

    - name: Building project
      run: npm run build-on:${GITHUB_REF##*/}

    - name: Archive build as artifact
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/test'
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: homework

      - name: Deploy to S3
        run: echo ${{secrets.AWS_S3_TEST_BUCKET}}