name: Check tests

on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [ test, master, develop, demo ]

jobs:
  running_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16.x]
    env:
      working-directory: front-end

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing dependencies
      run: npm install
      working-directory: ${{env.working-directory}}

    - name: Running tests
      run: npm test
      working-directory: ${{env.working-directory}}
