name: Deploy to test

on:
  push:
    branches: [ test, master, demo ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - run: npm run build-on:${GITHUB_REF##*/}
    - name: Archive build as artifact for ${GITHUB_REF##*/} environment
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
